apiVersion: v1
kind: Service
metadata:
  name: oracle-web-app-service
spec:
  type: LoadBalancer
  selector:
    app: oracle
  ports:
    - name: app1-port
      protocol: TCP
      port: 3001
      targetPort: 3000
    - name: app2-port
      protocol: TCP
      port: 81
      targetPort: 80
  