apiVersion: v1 
kind: Service 
metadata:
  name: oracle-app-svc 
spec: 
  selector:
    app: oracle 
  ports:
    - name: oralce 
      port: 80
      targetPort: 80
      protocol: TCP 
  type: LoadBalancer    
    